
spring.datasource.url=jdbc:mysql://proyecto3-db.mysql.database.azure.com:3306/salud?useSSL=true
spring.datasource.username=Proyecto3
spring.datasource.password=Cenfotec2023
# cuando corre el proyecto hace update a los entitys
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true
